# List of directories to ignore. This is a prefix match,
# i.e. everything under a matched directory is ignored.
filter_dirs = [
  "/lib/firmware",
  "/lib/modules",
  "/usr/lib/.build-id",
  "/usr/lib/firmware",
  "/usr/lib/grub",
  "/usr/lib/modules",
  "/usr/share/app-info",
  "/usr/share/doc",
  "/usr/share/fonts",
  "/usr/share/icons",
  "/usr/share/openshift",
  "/usr/src/plugins",
  "/rootfs",
  "/sysroot",
]

# List of files to ignore. This is a strict match.
filter_files = [
  ### static binaries, no crypto
  "/usr/bin/grpc_health_probe",
  "/usr/bin/cdi-containerimage-server",
  "/usr/bin/dumb-init", # https://github.com/Yelp/dumb-init
  "/app/bin/dumb-init", # https://github.com/Yelp/dumb-init
  "/usr/bin/cpb",
  "/usr/bin/pinns",
  "/usr/bin/pod",
  "/usr/bin/tini-static",
  "/usr/local/bin/catatonit",
  "/usr/libexec/catatonit/catatonit",
  "/usr/sbin/build-locale-archive",
  "/usr/sbin/glibc_post_upgrade.x86_64",
  "/usr/sbin/sln",
  "/usr/src/multus-cni/rhel7/bin/multus",
  "/usr/src/whereabouts/rhel7/bin/whereabouts",
  "/usr/src/egress-router-cni/rhel7/bin/egress-router",
]

# List of images to ignore.
filter_images = [ ]

[[ignore_errors]]
error = "ErrNotDynLinked"
files = [
  "/sbin/ldconfig",
  "/usr/sbin/ldconfig",
]


# Payload Components

## [payload.ose-agent-installer-node-agent-container]
## filter_files = [
##   "/usr/libexec/catatonit/catatonit",
##   "/usr/bin/cpb",
##   "/usr/bin/pod",
## ]
##
## [payload.agent-installer-node-agent-container]
## filter_files = [ "/usr/bin/cpb" ]
##
## [payload.operator-lifecycle-manager-container]
## filter_files = [ "/usr/bin/cpb" ]
##
## [payload.openshift-enterprise-pod-container]
## filter_files = [ "/usr/bin/pod" ]

